inherit_from: .rubocop_todo.yml

Style/ModuleFunction:
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  MinDigits: 20
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 10
Layout/LineLength:
  Max: 80
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 150